package com.pau.simpleviewbinding;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Toast;

import com.pau.simpleviewbinding.databinding.ActivityMainBinding;

//Access Views: You can access the views directly from the binding object using their IDs.
//The views are already cast to the appropriate types, so you don't need to do any type casting.

//Inflate the View: In your activity or fragment, you can now inflate the view using the generated binding class.
//The name of the class is generated by converting the XML file name to camel case and appending "Binding" to it.
// For example, if your layout file is activity_main.xml, the generated class will be ActivityMainBinding.
public class MainActivity extends AppCompatActivity {

    private ActivityMainBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //let the binding happen
        binding = ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        binding.buttonBind.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(getApplicationContext(), "hey", Toast.LENGTH_SHORT).show();
            }
        });
    }
}





